name: oriksha_application
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  persistent_bottom_nav_bar:
  intl: ^0.19.0
  cupertino_icons: ^1.0.2
  toggle_switch: ^2.1.0
  flutter_launcher_icons: ^0.13.1
  http: 1.1.0
  connectivity_plus: ^2.3.6
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  image_picker: ^1.0.5
  device_info_plus: ^9.0.2
  permission_handler: ^10.4.3
  flutter_image_compress: ^2.1.0
  path_provider: ^2.1.1
  flutter_otp_text_field: ^1.1.1
  google_maps_flutter: ^2.5.0
  location: ^5.0.3
  flutter_polyline_points: ^2.0.0
  get: ^4.6.6
  gap: ^3.0.1
  dio: ^5.4.0
  hive: ^2.2.3
  flutter_switch: ^0.3.2
  mask_text_input_formatter: ^2.8.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  firebase_messaging: ^14.7.10
  flutter_rating_bar: ^4.0.1
  flutter_local_notifications: ^16.3.2
  circular_countdown_timer: ^0.2.3
  fluttertoast: ^8.2.4
  url_launcher: ^6.2.4
  geocoding: ^2.1.1
  google_mlkit_face_detection: ^0.9.0
  razorpay_flutter: ^1.3.6
  shimmer: ^3.0.0
  loading_animation_widget: ^1.2.0+4
  pull_to_refresh: ^2.0.0
  geolocator: ^10.1.0
  pin_input_text_field: ^4.5.1
  reviews_slider: ^2.0.0
  dropdown_button2: ^2.3.9
  flutter_pdfview:





dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/app_image/
    - assets/icons/
    - assets/icons/rabbit.png
    - assets/icons/usericon.png
    - assets/icons/riksha.png
    - assets/icons/pickupMarker.png
    - assets/icons/dropMarker.png
    - assets/app_image/Motor_vehicle_act_May_2023.pdf
    - assets/app_image/3_Privacy Policy.pdf
    - assets/app_image/2_Terms and Conditions.pdf
#  fonts:
#    - family: Exo2
#      fonts:
#        - asset: assets/fonts/Exo2-Regular.ttf
#        - asset: assets/fonts/Exo2-Bold.ttf
#    - family: Inter
#      fonts:
#        - asset: assets/fonts/Inter-Regular.ttf
#        - asset: assets/fonts/Inter-Bold.ttf
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_image/logo.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/app_image/logo.jpg"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/app_image/logo.jpg"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/app_image/logo.jpg"
